# generated by clj2nix-1.0.4
{ pkgs ? import <nixpkgs> {} }:
  
  let repos = [
        "https://repo.clojars.org/"
        "https://repo1.maven.org/"
        "http://central.maven.org/maven2/"
        "http://oss.sonatype.org/content/repositories/releases/"
        "http://oss.sonatype.org/content/repositories/public/"
        "http://repo.typesafe.com/typesafe/releases/"
      ];

  in rec {
      makePaths = {extraClasspaths ? []}: (builtins.map (dep: if builtins.hasAttr "jar" dep.path then dep.path.jar else dep.path) packages) ++ extraClasspaths;
      makeClasspaths = {extraClasspaths ? []}: builtins.concatStringsSep ":" (makePaths {inherit extraClasspaths;});

      packages = [
  {
    name = "org.clojure/clojure";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "clojure";
      groupId = "org.clojure";
      sha512 = "f28178179483531862afae13e246386f8fda081afa523d3c4ea3a083ab607d23575d38ecb9ec0ee7f4d65cbe39a119f680e6de4669bc9cf593aa92be0c61562b";
      version = "1.10.1";
    };
  }

  {
    name = "joda-time/joda-time";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "joda-time";
      groupId = "joda-time";
      sha512 = "3a6749ecd71ee8d5781821c36d77850a810e72ee33757ec4ee9e3d424676dced7eeb955a432f45edb3694dc14dbe1ee4c608545d6a445b29b86979a7c9829384";
      version = "2.9.9";
    };
  }

  {
    name = "commons-codec/commons-codec";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-codec";
      groupId = "commons-codec";
      sha512 = "d9586162b257386b5871e7e9ae255a38014a9efaeef5148de5e40a3b0200364dad8516bddd554352aa2e5337bec2cc11df88c76c4fdde96a40f3421aa60650d7";
      version = "1.11";
    };
  }

  {
    name = "org.clojure/core.specs.alpha";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "core.specs.alpha";
      groupId = "org.clojure";
      sha512 = "348c0ea0911bc0dcb08655e61b97ba040649b4b46c32a62aa84d0c29c245a8af5c16d44a4fa5455d6ab076f4bb5bbbe1ad3064a7befe583f13aeb9e32a169bf4";
      version = "0.2.44";
    };
  }

  {
    name = "org.clojure/spec.alpha";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "spec.alpha";
      groupId = "org.clojure";
      sha512 = "18c97fb2b74c0bc2ff4f6dc722a3edec539f882ee85d0addf22bbf7e6fe02605d63f40c2b8a2905868ccd6f96cfc36a65f5fb70ddac31c6ec93da228a456edbd";
      version = "0.2.176";
    };
  }

  {
    name = "commons-fileupload/commons-fileupload";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-fileupload";
      groupId = "commons-fileupload";
      sha512 = "a7ce44d1172b73e8d1b552fd8ff89cf0e74788193677381063ccd53fe1847f865e06bdb40ea1720e3e9791056d3fdd67b1107c7c6ab3a9fe587a52b0d6c5fc5a";
      version = "1.3.3";
    };
  }

  {
    name = "org.eclipse.jetty/jetty-http";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-http";
      groupId = "org.eclipse.jetty";
      sha512 = "4626b970aa4d04422db93a4847eb9749768042255e0ba4d4944e1a8ca854de9e5eb093fbf5f0c05b122b65885324a9afdb1819acfb936514848c0726537cd403";
      version = "9.4.12.v20180830";
    };
  }

  {
    name = "org.eclipse.jetty/jetty-util";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-util";
      groupId = "org.eclipse.jetty";
      sha512 = "37ab6c29e925138d09a99bba9ead16b693318d8e098f1cf19fb56438c5d96479410628a84fa5a6c410850226acf1542aeab2a4894cebc9af8afa021c767d71f0";
      version = "9.4.12.v20180830";
    };
  }

  {
    name = "com.fasterxml.jackson.dataformat/jackson-dataformat-cbor";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-dataformat-cbor";
      groupId = "com.fasterxml.jackson.dataformat";
      sha512 = "82695d50cd7df578388db52433f56c8533e5565d01d2c17cc18b26536367eedd7a249afe070249fdaf8fa02c3d1c06a542d0a4303696b4d1ddc4cdcb3145a7bc";
      version = "2.9.9";
    };
  }

  {
    name = "ring/ring-jetty-adapter";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-jetty-adapter";
      groupId = "ring";
      sha512 = "e31f649fa173b7faa60c4ab4a4c89c40144a030ce5a53f836eacbb1644ee0196fd8db36488a9a47b199216c338f101bf208b78b146b85c599db2c8621978b9fc";
      version = "1.7.1";
    };
  }

  {
    name = "ring/ring-json";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-json";
      groupId = "ring";
      sha512 = "3e8ffd2091b069a171a8a7383e2478683230b24481c5f725a0aa6407111fd7baba0367d4823fa245b4b134f4d47b79335f8869c8cf7e44fb11fec361fcc5cd40";
      version = "0.5.0";
    };
  }

  {
    name = "commons-io/commons-io";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-io";
      groupId = "commons-io";
      sha512 = "4de22e2a50711f756a5542474395d8619dca0a8be0407b722605005a1167f8c306bc5eef7f0b8252f5508c817c1ceb759171e4e18d4eb9697dfdd809ac39673f";
      version = "2.6";
    };
  }

  {
    name = "com.fasterxml.jackson.core/jackson-core";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-core";
      groupId = "com.fasterxml.jackson.core";
      sha512 = "d8beac9e71444bc795c9d99308ead3284a39aa161f825708da7dbdfce410d099c0bbc76c31c27adad540cf3bccf6826d539fcb157923efae84b10b3778b920a9";
      version = "2.9.9";
    };
  }

  {
    name = "clj-time/clj-time";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "clj-time";
      groupId = "clj-time";
      sha512 = "db37587cd15ca13c63a5e3937966bd8ebf98b76533ddee9a696337ba783d2db4c9b8f9f1f232f88de8394237d82e37167b2def75409df95d2d8ca428cd582621";
      version = "0.14.3";
    };
  }

  {
    name = "crypto-equality";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "crypto-equality";
      groupId = "crypto-equality";
      sha512 = "54cf3bd28f633665962bf6b41f5ccbf2634d0db210a739e10a7b12f635e13c7ef532efe1d5d8c0120bb46478bbd08000b179f4c2dd52123242dab79fea97d6a6";
      version = "1.0.0";
    };
  }

  {
    name = "pandect";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "pandect";
      groupId = "pandect";
      sha512 = "8c265289f46a94cf2400f05223cdd3f9faee9a39e6ed5a55a3e89b09334a61e928c0f27e2db834edf3b544e2148a511bccf1ef73132bd9263659bed381abb59a";
      version = "0.6.1";
    };
  }

  {
    name = "crypto-random/crypto-random";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "crypto-random";
      groupId = "crypto-random";
      sha512 = "0551fba1c86871b1e70fe80679d78f11bec678ccad07f7b40cc7de1e97a3ec11f7df43dd86508869765cb1a6b2b5aa5cac6d10a5d319a26df8f513ec2bfa29e8";
      version = "1.2.0";
    };
  }

  {
    name = "ring/ring-codec";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-codec";
      groupId = "ring";
      sha512 = "696a9ec9b66f6d28ed96b1d8dd1881c430a4465b0d351b0bf3864924026b56469ccd342357c41ab9db59eb1b09b345bd75173c1e543b10cd611f17a72e3fc1b8";
      version = "1.1.1";
    };
  }

  {
    name = "crypto-equality/crypto-equality";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "crypto-equality";
      groupId = "crypto-equality";
      sha512 = "54cf3bd28f633665962bf6b41f5ccbf2634d0db210a739e10a7b12f635e13c7ef532efe1d5d8c0120bb46478bbd08000b179f4c2dd52123242dab79fea97d6a6";
      version = "1.0.0";
    };
  }

  {
    name = "cheshire/cheshire";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "cheshire";
      groupId = "cheshire";
      sha512 = "762d678617e6b83951a219421091cb6ca44f2d73d7d11a2b595d978f43dff82527c2881ff3adb3507540e06cf49f098d2359b6158176c3fdfb9fedcf7919db04";
      version = "5.9.0";
    };
  }

  {
    name = "tigris/tigris";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "tigris";
      groupId = "tigris";
      sha512 = "5393fe3f656521a6760d289d9549ffb9e9c1a8a72b69878205d53763802afa8778f1cb8bed6899e0b9721de231a79b8b1254cc601c84f5374467f1cc4780a987";
      version = "0.1.1";
    };
  }

  {
    name = "org.eclipse.jetty/jetty-io";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-io";
      groupId = "org.eclipse.jetty";
      sha512 = "1444eddfb34ee78c374118e7c77d7c5b618b54af281a5382230ea661c906951bd17c9cd055e15bdd78fb3f0a9d7bb561326c2220c48c493cc88910c823026306";
      version = "9.4.12.v20180830";
    };
  }

  {
    name = "javax.servlet/javax.servlet-api";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "javax.servlet-api";
      groupId = "javax.servlet";
      sha512 = "32f7e3565c6cdf3d9a562f8fd597fe5059af0cf6b05b772a144a74bbc95927ac275eb38374538ec1c72adcce4c8e1e2c9f774a7b545db56b8085af0065e4a1e5";
      version = "3.1.0";
    };
  }

  {
    name = "ring/ring-servlet";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-servlet";
      groupId = "ring";
      sha512 = "a30d906b79619f58572a3e4ca9fc6d0e77228aa8c19db58d51d7ed2c7f5f6678bbe270aada295b6f593eedd3f225b0a43e746780eb0d9a7c875afd778c56fd11";
      version = "1.7.1";
    };
  }

  {
    name = "org.eclipse.jetty/jetty-server";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "jetty-server";
      groupId = "org.eclipse.jetty";
      sha512 = "19c0ea335efd54f6758b64725b4938cd124e60856b8966e1c60d33a5ebe3c62eea5babe5974c3a1b2c5ea49013ba5fc99aaa1a27e5a9c85e46f693fc679e5309";
      version = "9.4.12.v20180830";
    };
  }

  {
    name = "ring/ring-core";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "ring-core";
      groupId = "ring";
      sha512 = "14be43af9e9938b07f0cc22be431720043445a3f46ce9c72e67d81d724f54e2311436a732ba3c2bb0c8abafc2ef077c1778773f02f018cb537820dc89b8b5213";
      version = "1.7.1";
    };
  }

  {
    name = "com.fasterxml.jackson.dataformat/jackson-dataformat-smile";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "jackson-dataformat-smile";
      groupId = "com.fasterxml.jackson.dataformat";
      sha512 = "409c39b581fa758a65e1e5344f08ac5607f5e3af41c5a307e61f2d0e54ba85487cfe6a6bbbeaa89a99c9fca0240c9dc5676cb50635378ae796570eb3bb427fe0";
      version = "2.9.9";
    };
  }

  ];
  }
  